### ISSUE TITLE
Nodegit 0.12.2: Incompatible with the current libgit2 gentoo package tree versions

### ISSUE THREAD

**Issue by zaolin** [elprans/atom-overlay#2]

**Comment by elprans** [comment]
Can you provide more information please?

**Comment by zaolin** [comment]
Hey,

sorry overlooked that git diff didnt worked anymore. Current ebuild leads to:

index.js:62 Error: /usr/lib64/atom/app.asar.unpacked/node_modules/nodegit/build/Release/nodegit.node: undefined symbol: git_stash_apply_init_options
    at Error (native)
    at process.module.(anonymous function) [as dlopen](ATOM_SHELL_ASAR.js:159:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) [as .node](ATOM_SHELL_ASAR.js:170:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/lib64/atom/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/lib64/atom/app.asar/node_modules/nodegit/lib/nodegit.js:9:12)
    at Module._compile (/usr/lib64/atom/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js](/usr/lib64/atom/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/lib64/atom/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/lib64/atom/app.asar/src/git-repository-async.js:25:16)
    at Module._compile (/usr/lib64/atom/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js](/usr/lib64/atom/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/lib64/atom/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/lib64/atom/app.asar/src/git-repository.js:12:24)
    at Object.<anonymous> (/usr/lib64/atom/app.asar/src/git-repository.js:428:4)
    at Module._compile (/usr/lib64/atom/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js](/usr/lib64/atom/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/lib64/atom/app.asar/src/native-compile-cache.js:50:27)
