### ISSUE TITLE
=app-editors/atom-1.18.0: Cannot find module '../build/Release/git.node'

### ISSUE THREAD

**Issue by ghost** [elprans/atom-overlay#20]
Hi,

Atom is compiling fine, but when I run and try to install Atom's packages or check for updates, I get the following errors:

```
module.js:457
    throw err;
    ^

Error: Cannot find module '../build/Release/git.node'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib64/atom/app/apm/node_modules/git-utils/lib/git.js:8:16)
    at Object.<anonymous> (/usr/lib64/atom/app/apm/node_modules/git-utils/lib/git.js:371:4)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

Also, the list of installed packages doesn't show up, it just keep loading _ad infinitum_. I think it's related to the error above.

**Comment by elprans** [comment]
Fixed, please remerge.
