### ISSUE TITLE
"invalid code point value" in atom and vscode

### ISSUE THREAD

**Issue by PF4Public** [elprans/atom-overlay#41]
Opening php file in `atom` or `vscode` gives "invalid code point value" and syntax highlight is broken.
The exact error in vscode is:
```
[renderer1] [error] invalid code point value: Error: invalid code point value
    at Object.createOnigScanner (/usr/lib64/vscode/node_modules.asar/vscode-textmate/release/main.js:67:24)
    at Grammar.createOnigScanner (/usr/lib64/vscode/node_modules.asar/vscode-textmate/release/main.js:2478:30)
    at RegExpSourceList.compile (/usr/lib64/vscode/node_modules.asar/vscode-textmate/release/main.js:1853:38)
    at BeginEndRule.compile (/usr/lib64/vscode/node_modules.asar/vscode-textmate/release/main.js:2008:45)
    at matchRule (/usr/lib64/vscode/node_modules.asar/vscode-textmate/release/main.js:2724:28)
    at matchRuleOrInjections (/usr/lib64/vscode/node_modules.asar/vscode-textmate/release/main.js:2743:23)
    at scanNext (/usr/lib64/vscode/node_modules.asar/vscode-textmate/release/main.js:2833:17)
    at _tokenizeString (/usr/lib64/vscode/node_modules.asar/vscode-textmate/release/main.js:2826:9)
    at Grammar._tokenize (/usr/lib64/vscode/node_modules.asar/vscode-textmate/release/main.js:2582:25)
    at Grammar.tokenizeLine2 (/usr/lib64/vscode/node_modules.asar/vscode-textmate/release/main.js:2552:22)
    at D.tokenize2 (file:///usr/lib64/vscode/out/vs/workbench/workbench.main.js:4365:788)
    at h._updateTokensUntilLine (file:///usr/lib64/vscode/out/vs/workbench/workbench.main.js:1173:735)
    at h._tokenizeOneLine (file:///usr/lib64/vscode/out/vs/workbench/workbench.main.js:1173:187)
    at P._revalidateTokensNow (file:///usr/lib64/vscode/out/vs/workbench/workbench.main.js:1203:644)
    at P._warmUpTokens (file:///usr/lib64/vscode/out/vs/workbench/workbench.main.js:1203:327)
    at P._tokenizationListener.C.TokenizationRegistry.onDidChange.e (file:///usr/lib64/vscode/out/vs/workbench/workbench.main.js:1177:857)
    at d.fire (file:///usr/lib64/vscode/out/vs/workbench/workbench.main.js:77:983)
    at r.fire (file:///usr/lib64/vscode/out/vs/workbench/workbench.main.js:627:245)
    at register (file:///usr/lib64/vscode/out/vs/workbench/workbench.main.js:627:336)
    at _promises.set.t.then.t (file:///usr/lib64/vscode/out/vs/workbench/workbench.main.js:627:543)
```
Atom gives a similar error.

Binary distributed vscode works fine.

Could it be, that some of the modules, that are built from source need to be updated?

By the way, do you plan updating atom to the latest version?

**Comment by elprans** [comment]
This is probably a `dev-libs/oniguruma` issue.  Try updating it.  Also, please post a minimal snippet that triggers the error.

**Comment by PF4Public** [comment]
>This is probably a dev-libs/oniguruma issue.

It is already the latest: dev-libs/oniguruma-6.9.2

Couldn't it be `asar` or any other build dependencies? IIRC atom mentioned `asar` in an error message. Unfortunately I've unmerged both atom and electron 2, so I cannot recreate the error atm.

>Also, please post a minimal snippet that triggers the error.

As simple as `test.php`:
`<?php
`

**Comment by elprans** [comment]
I'm not getting the error on my end (in vscode 1.33.1)  Could it be some other extension that is messing things up?

**Comment by PF4Public** [comment]
>Could it be some other extension that is messing things up?

I've tried disabling extensions one by one until all the extensions are disabled. Then I started disabling built-in extensions and this error disappeared with:
>PHP Language Basics vscode.php Built-in

enabling it back returns the error
>in vscode 1.33.1

May I ask you to try 1.35.1?

Once again. Binary vscode 1.35.1 with the same extensions has no such issue.

**Comment by elprans** [comment]
I can reproduce with oniguruma-6.9.2, but not oniguruma-6.9.1, so this is a regression in that library

**Comment by PF4Public** [comment]
Thanks for identifying the cause. I've filled a bug in oniguruma.

**Comment by PF4Public** [comment]
Would it be helpful to blacklist oniguruma-6.9.2 in `atom` and `vscode` ebuilds until the bug in oniguruma is fixed?

**Comment by liamdennehy** [comment]
Also present in portage ``app-editors/atom-1.32.1``

Logged in Gentoo Bugs: https://bugs.gentoo.org/691818

**Comment by PF4Public** [comment]
After updating to dev-libs/oniguruma-6.9.3::gentoo this seems to be fixed…
